LOGIN_MODE_ANY = "any"  # Special accept all
LOGIN_MODE_BASIC_AUTH = "basic_auth"
LOGIN_MODE_OAUTH = "oauth"

# OAuth Types
LOGIN_MODE_GOOGLE = "google_oauth"
LOGIN_MODE_APPLE = "apple_oauth"
LOGIN_MODE_FACEBOOK = "facebook_oauth"

OAUTH_LOGIN_TYPES = [LOGIN_MODE_GOOGLE, LOGIN_MODE_APPLE]
# AUTH_LOGIN_TYPES = [ LOGIN_MODE_GOOGLE_OAUTH, LOGIN_MODE_APPLE_OAUTH, LOGIN_MODE_FACEBOOK_OAUTH ]

LOGIN_STATUS_DISABLED = 0  # No Access
LOGIN_STATUS_LIFETIME = 1
LOGIN_STATUS_SUBSCRIBER = 2
LOGIN_STATUS_NON_SUBSCRIBER = 3

LOGIN_ACCESS_ENABLED = [
    LOGIN_STATUS_LIFETIME,
    LOGIN_STATUS_SUBSCRIBER,
    LOGIN_STATUS_NON_SUBSCRIBER,
]

ROLE_ADMIN_READ_ONLY = "AdminRO"
ROLE_ADMIN_WRITER = "AdminRW"
ROLE_ADMIN_IMPERSONATE = "AdminImpersonate"  # Ability to impersonate users
ROLE_ADMIN_RAW_DATA = "AdminRawData"  # Ability to call the raw data APIS
ROLE_DEBUG = "Debug"  # Ability to see debug information

LEADERBOARD_TYPE_RANK_WINS = 0
LEADERBOARD_TYPE_RANK_WEIGHTED_WINS = 1

SYSTEM_USER = "SystemUser"
